apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-modex1-deploy
  labels:
    app: local-modex1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-modex1
  template:
    metadata:
      labels:
        app: local-modex1
    spec:
      containers:
        - name: app
          image: local/modex1:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /renderws/carltonData/cj2023/code/minikube/minikube-gs/localdev/go-mod-ex1/data
---
apiVersion: v1
kind: Service
metadata:
  name: local-modex1-svc
spec:
  type: NodePort
  selector:
    app: local-modex1
  ports:
    - name: local-modex1-port
      protocol: TCP
      port: 8080
      targetPort: 8080
